DROP TABLE IF EXISTS student CASCADE;
DROP TABLE IF EXISTS advisior CASCADE;
DROP TABLE IF EXISTS client CASCADE;
DROP TABLE IF EXISTS project CASCADE;
DROP TABLE IF EXISTS prefer_project_xref CASCADE;
DROP TABLE IF EXISTS prefer_teammate_xref CASCADE;
DROP TABLE IF EXISTS avoid_teammate_xref CASCADE;
